//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaCobro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaCobro()
        {
            this.Cobros = new HashSet<Cobro>();
        }
    
        public int CajaCobroId { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int OficinaId { get; set; }
        public int Correlativo { get; set; }
        public string MAC { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public Nullable<int> CobradorID { get; set; }
    
        public virtual Cobradore Cobradore { get; set; }
        public virtual Oficina Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobro> Cobros { get; set; }
    }
}
