//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallAvePa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallAvePa()
        {
            this.Postes = new HashSet<Poste>();
        }
    
        public int CallAvePasID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int BarrioColoniaID { get; set; }
        public string Tipo { get; set; }
    
        public virtual BarrioColonia BarrioColonia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poste> Postes { get; set; }
    }
}
