//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro
    {
        public int CobroID { get; set; }
        public int CajaCobroID { get; set; }
        public Nullable<int> CobradorID { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Digitado { get; set; }
        public int ClienteId { get; set; }
        public int TipoCobroID { get; set; }
        public Nullable<int> BancoID { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual CajaCobro CajaCobro { get; set; }
        public virtual Cobradore Cobradore { get; set; }
        public virtual TipoCobro TipoCobro { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
