//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int ConfiguracionID { get; set; }
        public int Dia_Corte { get; set; }
        public string RazonSocial { get; set; }
        public string RTN_Alfa { get; set; }
        public string RTN_Num { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    }
}
