//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoDet()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int ContratoID { get; set; }
        public int ClienteID { get; set; }
        public int TarifaID { get; set; }
        public int EstadoID { get; set; }
        public Nullable<int> Conexiones { get; set; }
        public string Serie { get; set; }
        public string MAC { get; set; }
        public string IpAddress { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tarifa Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
    }
}
