//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.ContratoDets = new HashSet<ContratoDet>();
        }
    
        public int ContratoID { get; set; }
        public int ClienteID { get; set; }
        public string Numero { get; set; }
        public int EstadoID { get; set; }
        public Nullable<System.DateTime> Fch_Contrato { get; set; }
        public Nullable<System.DateTime> Fch_Instalacion { get; set; }
        public Nullable<System.DateTime> Fch_Corte { get; set; }
        public Nullable<int> VendedorID { get; set; }
        public Nullable<int> TecnicoID { get; set; }
        public Nullable<int> PosteID { get; set; }
        public Nullable<int> NodoID { get; set; }
        public string Casa { get; set; }
        public string Bloque { get; set; }
        public string ClaveUbicacion { get; set; }
        public string Referencia { get; set; }
        public string Obs { get; set; }
        public Nullable<int> BarrioColoniaID { get; set; }
    
        public virtual BarrioColonia BarrioColonia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoDet> ContratoDets { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Nodo Nodo { get; set; }
        public virtual Poste Poste { get; set; }
        public virtual Vendedore Vendedore { get; set; }
        public virtual Tecnico Tecnico { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
