//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetMateriale
    {
        public int DetMaterialesID { get; set; }
        public Nullable<int> OrdenID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Observacion { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual OrdenesTrabajo OrdenesTrabajo { get; set; }
    }
}
