//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int ClienteID { get; set; }
        public int ContratoID { get; set; }
        public int TarifaID { get; set; }
        public string Periodo { get; set; }
        public decimal Monto { get; set; }
        public decimal Saldo { get; set; }
    
        public virtual ContratoDet ContratoDet { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
