//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesTrabajo()
        {
            this.DetMateriales = new HashSet<DetMateriale>();
        }
    
        public int OrdenID { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> FallaID { get; set; }
        public string DescripcionFalla { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<int> TecnicoID { get; set; }
        public Nullable<int> EstatusID { get; set; }
        public Nullable<System.DateTime> Fch_Creacion { get; set; }
        public Nullable<System.DateTime> Fch_Cierre { get; set; }
        public Nullable<int> AlmacenInID { get; set; }
        public string DescripcionSolucion { get; set; }
    
        public virtual Estatu Estatu { get; set; }
        public virtual Falla Falla { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetMateriale> DetMateriales { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
