//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poste()
        {
            this.Contratos = new HashSet<Contrato>();
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int PosteID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int BarrioColoniaID { get; set; }
        public Nullable<int> CallAveID { get; set; }
        public Nullable<int> CallAvePasID { get; set; }
        public Nullable<int> NodoID { get; set; }
    
        public virtual BarrioColonia BarrioColonia { get; set; }
        public virtual CallAve CallAve { get; set; }
        public virtual CallAvePa CallAvePa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual Nodo Nodo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
