//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WaterSensorEntities : DbContext
    {
        public WaterSensorEntities()
            : base("name=WaterSensorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SensorData> SensorDatas { get; set; }
    
        public virtual int guardaDatos(Nullable<int> medida)
        {
            var medidaParameter = medida.HasValue ?
                new ObjectParameter("medida", medida) :
                new ObjectParameter("medida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("guardaDatos", medidaParameter);
        }
    
        public virtual ObjectResult<sp_ObtieneValorMedido_Result> sp_ObtieneValorMedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtieneValorMedido_Result>("sp_ObtieneValorMedido");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ObtieneUltimoValor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ObtieneUltimoValor");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_totaldia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_totaldia");
        }
    }
}
