//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Tarifas = new HashSet<Tarifa>();
        }
    
        public int ServicioID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Recargo { get; set; }
        public Nullable<bool> CableB { get; set; }
        public Nullable<bool> CableD { get; set; }
        public Nullable<bool> Internet { get; set; }
        public Nullable<bool> Telefonia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa> Tarifas { get; set; }
    }
}
